menu:
  主页: /
  归档: /archives

widgets:
- search

cover:
  enable: true
  url: http://www.afuncoder.com/images/bg.jpg
   
excerpt_link: Read More

full_format: 'ddd, MMM D YYYY, h:mm:ss a'

addthis:
  enable: true
  pubid:
  facebook:
  twitter:
  google: true
  pinterest:

fancybox: true

google_analytics: UA-67289336-1
rss:

comment_provider:

# Duoshuo comment
duoshuo:
  short_name:

social:
  github: https://github.com/XJianfei/
  weibo: 
  google_plus: 

auto_change:
  enable: true
